# Generated by Django 5.0.6 on 2024-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=True),
        ),
    ]
