# Generated by Django 5.0.6 on 2024-05-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
