# Generated by Django 5.0.6 on 2024-05-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
