# Generated by Django 5.0.6 on 2024-05-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_task_id_alter_task_completion_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
